### ISSUE TITLE
New error - sequelize.import is not a function while npm start

### ISSUE THREAD

**Issue by akshaya-kd** [BestBuy/api-playground#26]
Getting Below error while performing npn start

D:\BestBuyAPI\api-playground>npm start

> api-playground@1.1.0 start
> node src/

D:\BestBuyAPI\api-playground\src\db\index.js:36
      var model = sequelize['import'](path.join(__dirname, file));
                                     ^

TypeError: sequelize.import is not a function
    at D:\BestBuyAPI\api-playground\src\db\index.js:36:38
    at Array.forEach (<anonymous>)
    at Function.setupDatabase (D:\BestBuyAPI\api-playground\src\db\index.js:35:6)
    at Function.configure (D:\BestBuyAPI\api-playground\node_modules\feathers\lib\application.js:150:8)
    at Function.module.exports (D:\BestBuyAPI\api-playground\src\services\index.js:11:7)
    at Function.configure (D:\BestBuyAPI\api-playground\node_modules\feathers\lib\application.js:150:8)
    at Object.<anonymous> (D:\BestBuyAPI\api-playground\src\app.js:31:4)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)

**Comment by akshaya-kd** [comment]
Please refer the below index file details

31. fs.readdirSync(__dirname)
32.  .filter(function (file) {
33.     return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
34.   })
35.   .forEach(function (file) {
36.      var model = sequelize['import'](path.join(__dirname, file));
37.      db[model.name] = model;
38.    });

**Comment by anktyagi** [comment]
Replace 
var model = sequelize['import'](path.join(__dirname, file));
to
var model = require(path.join(__dirname, file))(sequelize, Sequelize.DataTypes);
